{
 "title": "Energy_Weather",
 "time": { "from": "now-4d", "to": "now+3d" },
 "panels": [
  {
   "title": "Life Time Energy ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  lifetimedata AS \"time\",\n  lifetimedata\nFROM solaredge_overview_api\n"
    }
   ]
  },
  {
   "title": "Total Energy this year",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  lastyearenergy AS \"time\",\n  lastyearenergy\nFROM solaredge_overview_api\n"
    }
   ]
  },
  {
   "title": "Last Month Energy ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  lastmonthenergy AS \"time\",\n  lastmonthenergy\nFROM solaredge_overview_api\n"
    }
   ]
  },
  {
   "title": "Energy Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  lastdayenergy AS \"time\",\n  lastdayenergy\nFROM solaredge_overview_api\n"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  currentpower AS \"time\",\n  currentpower AS \"currentpower\"\nFROM solaredge_overview_api"
    }
   ]
  },
  {
   "title": "Solar Energy Prediction and Production (University of Oulu)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Energy_Weather",
   "type": "graph",
   "description": "Predicted Energy Weather data ",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Predicted Energy Weather data " }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(power_output_w) AS \"power_output_w\",\n  avg(power_output_f0_w) AS \"power_output_f0_w\",\n  avg(power_output_f10_w) AS \"power_output_f10_w\",\n  avg(power_output_f25_w) AS \"power_output_f25_w\",\n  avg(power_output_f50_w) AS \"power_output_f50_w\",\n  avg(power_output_f75_w) AS \"power_output_f75_w\",\n  avg(power_output_f90_w) AS \"power_output_f90_w\",\n  avg(power_output_f100_w) AS \"power_output_f100_w\"\nFROM fmi_data\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)\n"
    }
   ]
  },
  {
   "title": "Solar Production ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(DATE,$__interval),\n  avg(power) AS \"power\"\nFROM energy_power_production\nGROUP BY 1\nORDER BY $__timeGroup(DATE,$__interval)"
    }
   ]
  },
  {
   "title": "Energy_Weather",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(power_output_w) AS \"power_output_w\",\n  avg(power_output_f0_w) AS \"power_output_f0_w\",\n  avg(power_output_f10_w) AS \"power_output_f10_w\",\n  avg(power_output_f25_w) AS \"power_output_f25_w\",\n  avg(power_output_f50_w) AS \"power_output_f50_w\",\n  avg(power_output_f75_w) AS \"power_output_f75_w\",\n  avg(power_output_f90_w) AS \"power_output_f90_w\",\n  avg(power_output_f100_w) AS \"power_output_f100_w\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)\n"
    },
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  payload\nFROM consumption\nWHERE\n  $__timeFilter(time_stamp)\nORDER BY time_stamp"
    }
   ]
  },
  {
   "title": "Energy production ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(DATE,$__interval),\n  avg(energy) AS \"energy\"\nFROM energy_power_production\nGROUP BY 1\nORDER BY $__timeGroup(DATE,$__interval)"
    }
   ]
  },
  {
   "title": "Radiations ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(system_radiation_global_wm2) AS \"system_radiation_global_wm2\",\n  avg(system_radiation_direct_wm2) AS \"system_radiation_direct_wm2\",\n  avg(system_radiation_diffuse_wm2) AS \"system_radiation_diffuse_wm2\",\n  avg(radiation_global_wm2) AS \"radiation_global_wm2\",\n  avg(radiation_direct_wm2) AS \"radiation_direct_wm2\",\n  avg(radiation_diffuse_wm2) AS \"radiation_diffuse_wm2\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  },
  {
   "title": "Cloud Coverage High ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "High" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_cover_high) AS \"cloud_cover_total\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  },
  {
   "title": "Cloud Coverage Medium ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Medium " }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_cover_medium) AS \"cloud_cover_medium\"\nFROM energy_weather\nWHERE\n  $__timeFilter(forecast_time)\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  },
  {
   "title": "Cloud Coverage Low",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Low" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(cloud_cover_low) AS \"cloud_cover_low\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  },
  {
   "title": "Panel Temperature ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(System_temperature_c) AS \"System_temperature_c\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  },
  {
   "title": "Air Temperature ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(air_temperature_c) AS \"air_temperature_c\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  },
  {
   "title": "Nominal Output Efficiency ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(forecast_time,$__interval),\n  avg(nominal_output_efficiency) AS \"nominal_output_efficiency\"\nFROM energy_weather\nGROUP BY 1\nORDER BY $__timeGroup(forecast_time,$__interval)"
    }
   ]
  }
 ]
}